/// Calendar Apr-2021 to Mar-2026 with financial year (Apr-Mar).
table Date
	lineageTag: 598a0d22-db13-4e0a-8c29-80de739c97f5
	dataCategory: Time

	column Date
		isUnique
		dataType: dateTime
		formatString: dd-MMM-yyyy
		lineageTag: 030c5f66-bca0-4f2f-beda-9562d2cc5a06
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 99a15992-20ab-4029-9076-6686236b2806
		summarizeBy: none
		sourceColumn: Year

	column 'Month No'
		dataType: int64
		isHidden
		lineageTag: 67345808-6e70-42f3-8b09-b2415d638bf9
		summarizeBy: none
		sourceColumn: Month No

	column Month
		dataType: string
		lineageTag: 819a6daf-ea17-4f7a-a88b-f22f161a2dc4
		summarizeBy: none
		sortByColumn: 'Month No'
		sourceColumn: Month

	column 'Month Year'
		dataType: string
		lineageTag: b211d0f1-a317-421c-8c14-b8b81a21b8f2
		summarizeBy: none
		sortByColumn: 'Month Year Sort'
		sourceColumn: Month Year

	column 'Month Year Sort'
		dataType: int64
		isHidden
		lineageTag: 0d669bd2-0605-4368-b3bc-563ad2156ff6
		summarizeBy: none
		sourceColumn: Month Year Sort

	column 'Month Start'
		dataType: dateTime
		formatString: MMM-yyyy
		lineageTag: a972880a-96ca-4c84-a493-bd18b080540a
		summarizeBy: none
		sourceColumn: Month Start

	column Quarter
		dataType: string
		lineageTag: a7ad6427-7fbe-4d6a-8471-bef75a56e42a
		summarizeBy: none
		sourceColumn: Quarter

	column 'Financial Year'
		dataType: string
		lineageTag: a4d8fa27-6246-48f1-bc9e-313635dfaddd
		summarizeBy: none
		sourceColumn: Financial Year

	column 'FY Quarter'
		dataType: string
		lineageTag: 72f4e926-9eb4-41f8-8784-273e11778a4a
		summarizeBy: none
		sourceColumn: FY Quarter

	column 'FY Month No'
		dataType: int64
		isHidden
		lineageTag: f15bdc34-4e6c-4726-a9f4-7623405515fa
		summarizeBy: none
		sourceColumn: FY Month No

	partition Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Renamed = Table.TransformColumnNames(Headers, each Text.Replace(_, "_", " ")),
				    Typed = Table.TransformColumnTypes(Renamed, {{"Date", type date}, {"Year", Int64.Type}, {"Month No", Int64.Type}, {"Month", type text}, {"Month Year", type text}, {"Month Year Sort", Int64.Type}, {"Month Start", type date}, {"Quarter", type text}, {"Financial Year", type text}, {"FY Quarter", type text}, {"FY Month No", Int64.Type}}, "en-US")
				in
				    Typed
